export const RESPONSE_MESSAGES = Object.freeze({
  USER_CREATED:
    'USER CREATED, CHECK YOUR PROVIDED MAIL ADDRESS FOR VERIFICATION',
  LOGIN_SUCCESSFUL: 'LOGIN SUCCESSFUL',
  SUCCESSFULLY_RETRIEVED_USER: 'SUCCESSFULLY RETRIEVED USER',
});
