name: Build Image and Deploy to Northflank

# Build and deploy the application everytime someone pushes to the "master" branch.
on:
  pull_request:
    branches: ['main']

env:
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_USERNAME: omotomiwa
  PROJECT_ID: lexitar-gadgets-ecommerce-backend
  SERVICE_ID: lexitar-gadget-app
  CREDENTIALS_ID: github

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1 - Checkout the repository containing our application's source code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 - Authenticate us with the container registry we intend to push a image to.
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 4 - Build the Docker image and push it to the container registry we previously authenticated with.
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      # Step 5 - Deploy the image to an existing Northflank service or job.
      - name: Deploy to Northflank
        uses: northflank/deploy-to-northflank@v1
        with:
          northflank-api-key: ${{ secrets.NORTHFLANK_API_KEY }}
          project-id: ${{ env.PROJECT_ID }}
          service-id: ${{ env.SERVICE_ID }}
          image-path: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          credentials-id: ${{ env.CREDENTIALS_ID }}
